name: Release Version

on:
  workflow_call:
    outputs:
      release-version: 
        value: ${{ jobs.release-version.outputs.release-version }}

jobs:
  release-version:
    name: Release Version
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.set-release-version.outputs.RELEASE_VERSION }}
    steps:
      - name: Set Release Version
        id: set-release-version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT